const menu = [
    {
      id: 1,
      title: 'Hủ tiếu',
      category: 'đồ ăn sáng',
      price: 30000,
      img: './images/item-1.jpeg',
      desc: `Hủ tiếu là một trong những món ăn sáng ngon nhất ở Sài Gòn rất được yêu thích. Sáng sớm dạy làm một tô hủ tiếu cho ấm bụng rồi sau đó bạn sẽ có đầy năng lượng để bắt đầu một ngày dài làm việc cực nhọc rồi.`,
    },
    {
      id: 2,
      title: 'Bánh mì',
      category: 'đồ ăn sáng',
      price: 20000,
      img: './images/item-2.jpeg',
      desc: `Bánh mì là một món ăn đường phố Việt Nam nổi tiếng và ở Sài Gòn thì đây cũng là một món ăn sáng ngon phổ biến với mọi đối tượng từ người già, học sinh, sinh viên, người lao động, nhân viên văn phòng…`,
    },
    {
      id: 3,
      title: 'Bún bò',
      category: 'đồ ăn sáng',
      price: 30000,
      img: './images/item-3.jpeg',
      desc: `Bún bò tiếp tục là một sự lựa chọn về đồ ăn sáng ngon ở Sài Gòn mà bạn không thể bỏ qua. Bún bò được nấu theo nhiều cách để bạn có thể đổi vị từng ngày như bún bò nấu theo phong cách Nam Bộ, bún bò Huế, bún bò Nam Định hay bún bò Hà Nội.`,
    },
    {
      id: 4,
      title: 'Bún quậy',
      category: 'đồ ăn sáng',
      price: 30000,
      img: './images/item-4.jpeg',
      desc: `Bún quậy là một món ăn sáng ngon ở TP Hồ Chí Minh có cách chế biến độc đáo và món này thực chất có nguồn gốc từ Phú Quốc. Bún quậy có rất nhiều vị cho mọi người lựa chọn như bún quậy chả cá, bún quậy sứa, bún quậy bạch tuộc, bún quậy chả tôm, bún quậy bò mỹ…`,
    },
    {
      id: 5,
      title: 'bún chả',
      category: 'đồ ăn sáng',
      price: 30000,
      img: './images/item-5.jpeg',
      desc: `Bún chả tiếp tục là một món ăn sáng ngon ở Sài Gòn mà bạn không thể bỏ qua. Món này có nguồn gốc xuất phát ở Hà Nội nhưng vì nó dễ ăn và hợp khẩu vị người Sài Thành nên giờ bạn cũng không khó để tìm được một quán bún chả ngon cho bữa sáng.`,
    },
    {
      id: 6,
      title: 'Bún thịt nướng ',
      category: 'đồ ăn sáng',
      price: 25000,
      img: './images/item-6.jpeg',
      desc: `Người Sài Gòn ăn gì vào buổi sáng? Bún thịt nướng chính là một trong những đáp án cho câu hỏi này để bạn tham khảo. Bún thịt nướng ngon là ở thịt nướng ướp vừa vặn, mùi thơm cùng nước sốt chua ngọt đậm đà.`,
    },
    {
      id: 7,
      title: 'Cháo Lòng',
      category: 'đồ ăn sáng',
      price: 20000,
      img: './images/item-7.jpeg',
      desc: `Ăn sáng Sài Gòn với món cháo lòng cũng là một sự lựa chọn mới mẻ mà bạn có thể cân nhắc. Cháo lòng là món dễ ăn tuy nhiên phải ăn nóng mới ngon, trong tô cháo lòng chủ yếu kèm theo các món nội tạng như tiết, dồi, lòng, gan, dạ giày, thịt dải, phổi heo…`,
    },
    {
      id: 8,
      title: 'Bánh canh',
      category: 'đồ ăn sáng',
      price: 25000,
      img: './images/item-8.jpeg',
      desc: `Bánh canh thì chắc không còn xa lạ gì với người Sài Gòn nữa rồi. Nếu như bạn đi Sài Gòn thì chắc chắn sẽ không khó để tìm được một quán bánh canh ăn sáng, nhất là các khu chợ thì lại càng nhiều. Bánh canh có những sự lựa chọn như bánh canh ghẹ, bánh canh cua, bánh canh tôm…`,
    },
    {
      id: 9,
      title: 'cơm tấm',
      category: 'đồ ăn trưa',
      price: 30000,
      img: './images/item-9.jpeg',
      desc: `Cơm cơm là địa chỉ đầu tiên trong danh sách mà Foodi gợi ý cho bạn, bởi vì thật thiếu sót nếu không đề cập đến món ăn dân tộc này, phải không? Một đĩa cơm đầy đủ truyền thống bao gồm cơm mềm mềm dẻo, sườn băm nhỏ ướp với các loại gia vị, trứng cuộn thơm ăn kèm với tương ớt tỏi là không dễ từ chối! Ngoài ra, nếu bạn cảm thấy phấn khích, bạn có thể chọn cơm sườn với 4 món hoặc 5 xương sườn, đảm bảo bạn không về nhà!`,
    },
    {
      id: 10,
      title: 'Cơm gà béo ngậy',
      category: 'đồ ăn trưa',
      price: 30000,
      img: './images/item-10.jpeg',
      desc: `Gà mỡ mỡ nhà hàng 142 được coi là một trong Thanh ăn trưa sài gòn Đắt nhất. Lý do vô cùng đơn giản, liệu bạn có thể dừng lại trước một miếng cơm gà vàng ươm với phần trên đùi đùi vẫn còn bốc mùi hôi thối nhưng vẫn bốc khói nhưng chỉ với tầm 30.000 đến 40.000 đồng? Nếu bạn không ăn cơm gà trong một thời gian dài, hãy lưu địa chỉ 142 Ba Đình ngay bây giờ!`,
    },
    {
      id: 11,
      title: 'súp cua',
      category: 'đồ ăn trưa',
      price: 30000,
      img: './images/item-11.jpeg',
      desc: `Bánh súp được thực khách nhận xét là ngon và nước dùng đậm đà. Đặc biệt phải kể đến là những siêu thực phẩm bao gồm: cua, xúc xích, tôm, thịt, … luôn được lựa chọn cẩn thận và khi ăn vẫn có hương vị tươi ngon.`,
    },
    {
      id: 12,
      title: 'Phở bò cũ',
      category: 'đồ ăn trưa',
      price: 30000,
      img: './images/item-12.jpeg',
      desc: `Một món ăn Ăn trưa sài gòn Gợi ý tiếp theo của Foodi cho bạn là phở bò. Đến với 169 Cao Thắng, bạn sẽ được thưởng thức ngay một bát mì gạo với cái miệng lạ, nước dùng ngọt và thơm đúng với hương vị của Huế xưa và rất nhiều topping, rau sống hấp dẫn. Thêm một chút ớt, sa tế để tăng hương vị, còn ai có thể từ chối?`,
    },
    {
      id: 13,
      title: 'Strongbow úp ngược vị hoa quả',
      category: 'đồ uống',
      price: 40000,
      img: './images/item-13.jpeg',
      desc: `Bún bò tiếp tục là một sự lựa chọn về đồ ăn sáng ngon ở Sài Gòn mà bạn không thể bỏ qua. Bún bò được nấu theo nhiều cách để bạn có thể đổi vị từng ngày như bún bò nấu theo phong cách Nam Bộ, bún bò Huế, bún bò Nam Định hay bún bò Hà Nội.`,
    },
    {
      id: 14,
      title: 'Nước lê Hà Khẩu',
      category: 'đồ uống',
      price: 35000,
      img: './images/item-14.jpeg',
      desc: `Mới nổi trong giới đồ uống Hot nhất Hà Nội là nước lê Hà khẩu. Nước ngọt thoang thoảng man mát, thơm nhẹ mùi lê . Để vào tủ lạnh rồi uống là quên sầu luôn. Nước lê này ngon chuẩn vị lê, không đường hoá học – không chất tạo mùi. Sáng đi làm hay đi học để một chai và tủ ướp lạnh. Tối về mở tủ lạnh là có ngay thưc uống ngọt thanh mát mát vị lê. Uống giải khát như nước hoa quả hay uống thay nước lọc đều tuyệt vời.`,
    },
    {
      id: 15,
      title: 'Rau má đậu xanh',
      category: 'đồ uống',
      price: 20000,
      img: './images/item-15.png',
      desc: `Tiệm Rau Má – MAXH lại đem đến một cảm giác cực mới lạ và hấp dẫn menu có rất nhiều loại nước rau má phong phú như là rau má chanh leo, rau má đậu xanh, rau má sầu riêng,.. kết hợp cùng nhiều loại topping như trân châu socola, milk farm, pudding,.. Ưng nhất là rau má sầu riêng, vị thanh mát của rau má kèm theo mùi thơm thơm của sầu riêng mang lại sự hòa quyện vô cùng thú vị.`,
    },
    {
      id: 16,
      title: 'Trà sữa lon – Master Tea',
      category: 'đồ uống',
      price: 30000,
      img: './images/item-16.jpeg',
      desc: `Trà sữa nắp cầu, trà sữa bóng đèn hay trà sữa nút trái tim đã xưa rồi, bây giờ là “thời” của trà sữa lon. Trà sữa được đóng gói trong lon vô cùng đẹp mắt, nhỏ nhắn, dễ dàng mang theo nhưng vô cùng “sang chảnh”. Trà sữa uống ở mức ổn, đối với dòng trà hoa quả các bạn nên giảm đường nhé, sẽ ngon hơn đó. Trân châu đường đen, nha đam cùng các loại topping khác cũng khá ngon.`,
    },
    {
      id: 17,
      title: 'Bia trân châu kem cheese',
      category: 'đồ uống',
      price: 40000,
      img: './images/item-17.jpeg',
      desc: `Đến Shogun để thử loại bia thần thánh lần đầu xuất hiện tại Việt Nam nhé! Tapioca beer còn gọi là bia trân châu kem cheese với sự kết hợp đầy nghệ thuật giữa bia Nhật. Hòa quyện trái cây thơm ngon, lớp kem cheese sánh mịn bên trên và dưới cùng là trân châu đường đen bùi dẻo. Tất cả đã tạo nên một loại thức uống độc đáo đầy hấp dẫn. Có 3 loại hương vị: Việt quất, quýt, nhiệt đới tha hồ cho bạn lựa chọn.`,
    },
    {
      id: 18,
      title: 'Nước mía trân châu dừa tươi',
      category: 'đồ uống',
      price: 30000,
      img: './images/item-18.jpeg',
      desc: `Nước mía trân châu dừa tươi. Nước mía ở đây theo cảm nhận của nhiều người là ngọt, nhưng ngọt dịu. Trân châu được nấu ổn, chín tới và nấu mới trong ngày luôn nên ăn dẻo, mềm và dai. Về dừa tươi nạo sợi, quán dùng dừa khô loại to dày và phủ đều trên cốc nước mía. Chỉ thế thôi nhưng cũng làm tăng thêm độ ngọt của thức uống.`,
    },
    {
      id: 19,
      title: 'Trà sữa nướng ngũ vị',
      category: 'đồ uống',
      price: 45000,
      img: './images/item-19.jpeg',
      desc: `Hồng trà sữa nướng nhờ vị trà đậm đặc trưng. Hoà quyện cùng sự ngậy ngậy sương sương của đường nướng theo công thức đặc biệt. Điều đó đã giúp Hồng trà sữa nướng có thể giữ nguyên hương vị hoàn hảo lên tới 4 tiếng, không lo bị nhạt vị.`,
    },
  ];
  export default menu;
  